version: v2
name: Prettier
slug: prettier
type: content
summary: Keep files formatted with Prettier
description: Keep files formatted with Prettier
beta: true
subscription_level: 1
default_configuration:
  installation:
    org: true
memory: 512
timeout: 240
subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested
  - check_run.requested_action
