name: Prettier
slug: prettier
summary: Opinionated Code Formatter that supports many languages
description: |
  <a href="https://prettier.io">Prettier</a> is a popular code formatter that supports many languages.
  <br>
  <br>
  One of the main inspirations for creating it was to eliminate bikeshedding over style. The tool is opinionated for this reason.
  If you're interested in learning more about Prettier check out their <a href="https://prettier.io/docs/en/why-prettier.html">documentation</a> for
  a more in-depth explanation.
  <br>
  <br>
  Githaxs recommends you use the default Prettier settings without any changes to avoid the bikeshedding discussions.

capabilities:
  - type: checkout
  - type: checkrun
    fix_errors: true
runtime: bash
show: all
parameters:
  - name: prettier_config
    description: "A publicly available NPM package where your shared prettier config is published (i.e. @azz/prettier-config)"
beta: false
subscription_level: 1
default_configuration:
  installation:
    org: false
memory: 2048
timeout: 240
packages:
  node:
    - prettier